services:
  - type: worker
    name: agrobalance-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot/agrobot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: USER_TELEGRAM_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"

